#ifndef CONFIGURACION_H
#define CONFIGURACION_H

#define NOMBRE_SISTEMA "Sistema de Gestion de Biblioteca"

#define OPCION_MENU_OPERATIVAS 1
#define OPCION_MENU_GENERALES 2
#define OPCION_MENU_SALIR 3

#define OPCION_VOLVER_OPERATIVAS 6
#define OPCION_VOLVER_GENERALES 5

#define TAMANIO_BLOQUE_LECTURA 32

#define SISTEMA_ACTIVO 1
#define SISTEMA_INACTIVO 0

#endif