#ifndef CONFIGURACION_H
#define CONFIGURACION_H

#define NOMBRE_SISTEMA "Sistema de Gestion de Biblioteca"

#define OPCION_MENU_OPERATIVAS 1
#define OPCION_MENU_GENERALES 2
#define OPCION_MENU_SALIR 3

#define OPCION_VOLVER_OPERATIVAS 6
#define OPCION_VOLVER_GENERALES 5

#define OPCION_CATALOGO_CARGAR_LOTE 1
#define OPCION_CATALOGO_VER 2
#define OPCION_CATALOGO_VOLVER 3

#define OPCION_USUARIO_CREAR 1
#define OPCION_USUARIO_VER 2
#define OPCION_USUARIO_MODIFICAR 3
#define OPCION_USUARIO_ELIMINAR 4
#define OPCION_USUARIO_VOLVER 5

#define TAMANIO_BLOQUE_LECTURA 32

#define SISTEMA_ACTIVO 1
#define SISTEMA_INACTIVO 0

#define ARCHIVO_CATALOGO "catalogo.json"
#define ARCHIVO_USUARIOS "usuarios.json"
#define ARCHIVO_PRESTAMOS "prestamos.json"

#define ANIO_MINIMO 1000
#define ANIO_MAXIMO 2100

#define CANTIDAD_MINIMA 1

#define DIAS_PROXIMO_VENCIMIENTO 5

#endif